version: '2'

services:
  board-ui:
    image: nginx:alpine
    volumes:
      - /content/board-ui/src:/usr/share/nginx/html
    ports:
      - "8080:80"
  #environment:
  # - NGINX_HOST=foobar.com
  # - NGINX_PORT=80
  #command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"