version: '2'

services:
  board-ui:
    image: eugenekha/board-ui:latest
    volumes:
      - /content/board/board-ui/src:/usr/share/nginx/html
    #ports:
    #  - "8081:80"
    network_mode: "bridge"
  #environment:
  # - NGINX_HOST=foobar.com
  # - NGINX_PORT=80
  #command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"